version: "3"
services:
  mysql:
    image: mysql:5.7
    container_name: "mysql57"
    environment:
      MYSQL_DATABASE: "taskmanager"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "abcd1234"
      MYSQL_ROOT_PASSWORD: "abcd1234"
    ports:
      # HOST:CONTAINER
      - "3357:3306"
    volumes:
      - /var/lib/mysql